trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  webAppName: 'your-app-service-name'  # Replace with your actual Azure App Service name
  resourceGroup: 'your-resource-group-name'  # Replace with your Resource Group

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/static-gym-html-css-app'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '<your-service-connection-name>'
              appType: 'webApp'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop'
